# Generated by Django 3.1.3 on 2021-10-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0009_auto_20211031_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
